# Generated by Django 2.1.4 on 2019-08-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPVS_CONFIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(max_length=100, verbose_name='VIP')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('scheduler', models.CharField(choices=[('sh', '地址哈希'), ('rr', '轮训'), ('wrr', '加权轮询'), ('lc', '最少连接'), ('wlc', '加权最少链接')], max_length=10, verbose_name='调度算法')),
                ('protocol', models.CharField(choices=[('-t', 'TCP'), ('-u', 'UDP')], default='-t', max_length=10, verbose_name='tcp/udp')),
                ('persistence', models.IntegerField(blank=True, null=True, verbose_name='转发模式')),
                ('line', models.CharField(blank=True, max_length=100, null=True, verbose_name='线路描述')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('is_active', models.SmallIntegerField(default=0, verbose_name='激活')),
                ('ipvs_assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipvs_total', to='asset.Assets', verbose_name='assets_id')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': 'IPVS信息表',
                'db_table': 'opsmanage_ipvs_config',
                'permissions': (('ipvs_read_ipvs_config', '读取IPVS信息表权限'), ('ipvs_change_ipvs_config', '更改IPVS信息表权限'), ('ipvs_add_ipvs_config', '添加IPVS信息表权限'), ('ipvs_delete_ipvs_config', '删除IPVS信息表权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IPVS_NS_CONFIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameserver', models.CharField(blank=True, max_length=100, null=True, verbose_name='nameserver')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('ipvs_vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipvs_ns_total', to='apply.IPVS_CONFIG', verbose_name='vip_id')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': 'IPVS_NS_信息表',
                'db_table': 'opsmanage_ipvs_ns_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IPVS_OPS_LOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='操作用户')),
                ('cmd', models.CharField(max_length=500, verbose_name='VIP')),
                ('status', models.IntegerField(default=0, verbose_name='操作状态')),
                ('ipvs_vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipvs_ops_total', to='apply.IPVS_CONFIG', verbose_name='vip_id')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': 'IPVS操作记录表',
                'db_table': 'opsmanage_ipvs_ops_log',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IPVS_RS_CONFIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipvs_fw_ip', models.CharField(max_length=100, verbose_name='VIP')),
                ('forword', models.CharField(choices=[('-m', 'NAT'), ('-g', 'DR'), ('-i', 'TUN'), ('-b', 'FULLNAT')], max_length=10, verbose_name='转发模式')),
                ('weight', models.SmallIntegerField(default=0, verbose_name='权重')),
                ('is_active', models.IntegerField(default=0, verbose_name='激活')),
                ('ipvs_vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipvs_rs', to='apply.IPVS_CONFIG', verbose_name='vip_id')),
                ('rs_assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipvs_realserver_total', to='asset.Assets', verbose_name='assets_id')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': 'IPVS_RS_信息表',
                'db_table': 'opsmanage_ipvs_rs_config',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='ipvs_rs_config',
            unique_together={('ipvs_vip', 'ipvs_fw_ip')},
        ),
        migrations.AlterUniqueTogether(
            name='ipvs_ns_config',
            unique_together={('ipvs_vip', 'nameserver')},
        ),
        migrations.AlterUniqueTogether(
            name='ipvs_config',
            unique_together={('vip', 'port', 'ipvs_assets')},
        ),
    ]
