# Generated by Django 2.1.4 on 2019-08-03 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy_CallBack_Model_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='输出内容')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署剧本操作记录表',
                'db_table': 'opsmanage_deploy_callback_model_result',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Deploy_CallBack_PlayBook_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='输出内容')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署剧本操作记录详情表',
                'db_table': 'opsmanage_deploy_callback_playbook_result',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Deploy_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='资产名称')),
                ('desc', models.CharField(max_length=200, verbose_name='功能描述')),
                ('user', models.SmallIntegerField(verbose_name='创建人')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署资产表',
                'db_table': 'opsmanage_deploy_inventory',
                'permissions': (('deploy_read_deploy_inventory', '读取部署资产权限'), ('deploy_change_deploy_inventory', '修改部署资产权限'), ('deploy_add_deploy_inventory', '添加部署资产权限'), ('deploy_delete_deploy_inventory', '删除部署资产权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Deploy_Inventory_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='group name')),
                ('ext_vars', models.TextField(blank=True, null=True, verbose_name='组外部变量')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_group', to='deploy.Deploy_Inventory')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署资产成员表',
                'db_table': 'opsmanage_deploy_inventory_groups',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Deploy_Inventory_Groups_Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.SmallIntegerField(verbose_name='服务器')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_group_server', to='deploy.Deploy_Inventory_Groups')),
            ],
            options={
                'db_table': 'opsmanage_deploy_inventory_groups_servers',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Deploy_Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=50, unique=True, verbose_name='剧本名称')),
                ('playbook_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='功能描述')),
                ('playbook_vars', models.TextField(blank=True, null=True, verbose_name='模块参数')),
                ('playbook_uuid', models.CharField(max_length=50, verbose_name='唯一id')),
                ('playbook_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='服务器选择类型')),
                ('playbook_file', models.FileField(upload_to='./playbook/', verbose_name='剧本路径')),
                ('playbook_service', models.SmallIntegerField(blank=True, null=True, verbose_name='授权业务')),
                ('playbook_user', models.SmallIntegerField(blank=True, null=True, verbose_name='授权用户')),
                ('playbook_server', models.TextField(blank=True, null=True, verbose_name='目标机器')),
                ('playbook_group', models.SmallIntegerField(blank=True, null=True, verbose_name='授权组')),
                ('playbook_tags', models.SmallIntegerField(blank=True, null=True, verbose_name='资产标签')),
                ('playbook_inventory_groups', models.SmallIntegerField(blank=True, null=True, verbose_name='资产组')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署剧本配置表',
                'db_table': 'opsmanage_deploy_playbook',
                'permissions': (('deploy_read_deploy_playbook', '读取部署剧本权限'), ('deploy_change_deploy_playbook', '修改部署剧本权限'), ('deploy_add_deploy_playbook', '添加部署剧本权限'), ('deploy_delete_deploy_playbook', '删除部署剧本权限'), ('deploy_exec_deploy_playbook', '执行部署剧本权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Deploy_Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=50, unique=True, verbose_name='脚本名称')),
                ('script_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='唯一id')),
                ('script_server', models.TextField(blank=True, null=True, verbose_name='目标机器')),
                ('script_file', models.FileField(upload_to='./scripts/', verbose_name='脚本路径')),
                ('script_args', models.TextField(blank=True, null=True, verbose_name='脚本参数')),
                ('script_service', models.SmallIntegerField(blank=True, null=True, verbose_name='授权业务')),
                ('script_user', models.SmallIntegerField(blank=True, null=True, verbose_name='添加人')),
                ('script_group', models.SmallIntegerField(blank=True, null=True, verbose_name='授权组')),
                ('script_tags', models.SmallIntegerField(blank=True, null=True, verbose_name='资产标签')),
                ('script_inventory_groups', models.SmallIntegerField(blank=True, null=True, verbose_name='资产组')),
                ('script_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='脚本类型')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署脚本配置表',
                'db_table': 'opsmanage_deploy_script',
                'permissions': (('deploy_read_deploy_script', '读取部署脚本权限'), ('deploy_change_deploy_script', '修改部署脚本权限'), ('deploy_add_deploy_script', '添加部署脚本权限'), ('deploy_delete_deploy_script', '删除部署脚本权限'), ('deploy_exec_deploy_script', '执行部署脚本权限'), ('deploy_exec_deploy_model', '执行部署模块权限'), ('deploy_read_deploy_model', '读取部署模块权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Log_Deploy_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_user', models.CharField(default=None, max_length=50, verbose_name='使用用户')),
                ('ans_model', models.CharField(default=None, max_length=100, verbose_name='模块名称')),
                ('ans_args', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='模块参数')),
                ('ans_server', models.TextField(default=None, verbose_name='服务器')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': 'Ansible模块执行记录表',
                'db_table': 'opsmanage_log_deploy_model',
                'permissions': (('deploy_read_log_deploy_model', '读取部署模块执行记录权限'), ('deploy_change_log_deploy_model', '修改部署模块执行记录权限'), ('deploy_add_log_deploy_model', '添加部署模块执行记录权限'), ('deploy_delete_log_deploy_model', '删除部署模块执行记录权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Log_Deploy_Playbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='id')),
                ('ans_user', models.CharField(default=None, max_length=50, verbose_name='使用用户')),
                ('ans_name', models.CharField(default=None, max_length=100, verbose_name='模块名称')),
                ('ans_content', models.CharField(default=None, max_length=200)),
                ('ans_server', models.TextField(default=None, verbose_name='服务器')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '应用部署管理',
                'verbose_name_plural': '部署剧本操作记录表',
                'db_table': 'opsmanage_log_deploy_playbook',
                'permissions': (('deploy_read_log_deploy_playbook', '读取部署剧本执行记录权限'), ('deploy_change_log_deploy_playbook', '修改部署剧本执行记录权限'), ('deploy_add_log_deploy_playbook', '添加部署剧本执行记录权限'), ('deploy_delete_log_deploy_playbook', '删除部署剧本执行记录权限')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='deploy_callback_playbook_result',
            name='logId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Log_Deploy_Playbook'),
        ),
        migrations.AddField(
            model_name='deploy_callback_model_result',
            name='logId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Log_Deploy_Model'),
        ),
        migrations.AlterUniqueTogether(
            name='deploy_inventory_groups_server',
            unique_together={('groups', 'server')},
        ),
        migrations.AlterUniqueTogether(
            name='deploy_inventory_groups',
            unique_together={('inventory', 'group_name')},
        ),
    ]
