# Generated by Django 2.1.4 on 2019-08-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_minute', models.CharField(default=None, max_length=10, verbose_name='分')),
                ('cron_hour', models.CharField(default=None, max_length=10, verbose_name='时')),
                ('cron_day', models.CharField(default=None, max_length=10, verbose_name='天')),
                ('cron_week', models.CharField(default=None, max_length=10, verbose_name='周')),
                ('cron_month', models.CharField(default=None, max_length=10, verbose_name='月')),
                ('cron_user', models.CharField(default=None, max_length=50, verbose_name='任务用户')),
                ('cron_name', models.CharField(default=None, max_length=100, verbose_name='任务名称')),
                ('cron_log_path', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='任务日志路径')),
                ('cron_type', models.CharField(default=None, max_length=10, verbose_name='任务类型')),
                ('cron_command', models.CharField(default=None, max_length=200, verbose_name='任务参数')),
                ('cron_script', models.FileField(blank=True, default=None, null=True, upload_to='./cron/', verbose_name='脚本路径')),
                ('cron_script_path', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='脚本路径')),
                ('cron_status', models.SmallIntegerField(default=None, verbose_name='任务状态')),
                ('cron_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crontab_total', to='asset.Assets')),
            ],
            options={
                'verbose_name': '计划任务管理',
                'verbose_name_plural': '任务配置表',
                'db_table': 'opsmanage_cron_config',
                'permissions': (('sched_can_read_cron_config', '读取任务配置权限'), ('sched_can_change_cron_config', '更改任务配置权限'), ('sched_can_add_cron_config', '添加任务配置权限'), ('sched_can_delete_cron_config', '删除任务配置权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Log_Cron_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='id')),
                ('cron_user', models.CharField(default=None, max_length=50, verbose_name='操作用户')),
                ('cron_name', models.CharField(default=None, max_length=100, verbose_name='名称')),
                ('cron_content', models.CharField(default=None, max_length=100)),
                ('cron_server', models.CharField(default=None, max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '计划任务管理',
                'verbose_name_plural': '任务配置操作记录表',
                'db_table': 'opsmanage_log_cron_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sched_Job_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, unique=True, verbose_name='任务id')),
                ('job_name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('second', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='分')),
                ('minute', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='时')),
                ('hour', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='天')),
                ('week', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='第几周')),
                ('day', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='周')),
                ('month', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='月')),
                ('year', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='年')),
                ('day_of_week', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='星期几')),
                ('job_command', models.TextField(verbose_name='任务参数')),
                ('start_date', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='开始时间')),
                ('end_date', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='结束时间')),
                ('run_date', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='指定时间')),
                ('sched_type', models.CharField(choices=[('date', '日期'), ('interval', '间隔'), ('cron', 'crontab')], max_length=10, verbose_name='调度类型')),
                ('status', models.CharField(choices=[('running', '运行'), ('stopped', '停止')], max_length=10, verbose_name='任务状态')),
                ('is_alert', models.SmallIntegerField(default=0, verbose_name='执行失败是否通知')),
                ('notice_trigger', models.SmallIntegerField(blank=True, choices=[(0, '失败'), (1, '成功'), (2, '完成')], default=0, null=True, verbose_name='触发类型')),
                ('notice_type', models.SmallIntegerField(blank=True, choices=[(0, '邮箱'), (1, '微信'), (2, '钉钉')], default=0, null=True, verbose_name='通知类型')),
                ('notice_interval', models.IntegerField(blank=True, default=3600, null=True, verbose_name='通知间隔')),
                ('notice_number', models.TextField(blank=True, default=None, null=True, verbose_name='通知人')),
                ('atime', models.IntegerField(blank=True, null=True, verbose_name='告警时间')),
            ],
            options={
                'verbose_name': '计划任务管理',
                'verbose_name_plural': '任务配置表',
                'db_table': 'opsmanage_sched_job_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sched_Job_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(verbose_name='任务执行状态')),
                ('stime', models.IntegerField(verbose_name='开始时间')),
                ('etime', models.IntegerField(verbose_name='结束时间')),
                ('cmd', models.TextField(default=None, verbose_name='执行命令')),
                ('result', models.TextField(default=None, verbose_name='执行结果')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_jobs_log', to='sched.Sched_Job_Config')),
            ],
            options={
                'verbose_name': '计划任务管理',
                'verbose_name_plural': '任务执行日志表',
                'db_table': 'opsmanage_sched_job_logs',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sched_Node',
            fields=[
                ('sched_node', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.SmallIntegerField(verbose_name='端口')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='认证密码')),
                ('enable', models.SmallIntegerField(default=1, verbose_name='端口')),
                ('sched_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sched_node', to='asset.Assets')),
            ],
            options={
                'verbose_name': '计划任务管理',
                'verbose_name_plural': '任务节点表',
                'db_table': 'opsmanage_sched_node',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='sched_job_config',
            name='job_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_jobs', to='sched.Sched_Node'),
        ),
        migrations.AlterUniqueTogether(
            name='sched_node',
            unique_together={('sched_server', 'port')},
        ),
        migrations.AlterUniqueTogether(
            name='cron_config',
            unique_together={('cron_name', 'cron_server', 'cron_user')},
        ),
    ]
