# Generated by Django 2.1.4 on 2019-08-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Project_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='操作用户')),
                ('commit_id', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('servers', models.TextField(default=None, verbose_name='目标主机')),
                ('branch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(max_length=10)),
                ('type', models.CharField(blank=True, default='deploy', max_length=10, null=True)),
                ('task_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='唯一id')),
                ('package', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '项目发布管理',
                'verbose_name_plural': '项目配置操作日志配置表',
                'db_table': 'opsmanage_log_project_config',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Log_Project_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=50, verbose_name='操作类型')),
                ('msg', models.TextField(default=None, verbose_name='名称')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('status', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('task_id', models.CharField(db_index=True, max_length=50, verbose_name='唯一id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '项目发布管理',
                'verbose_name_plural': '项目配置操作记录表',
                'db_table': 'opsmanage_log_project_record',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_env', models.CharField(default=None, max_length=50, verbose_name='项目环境')),
                ('project_name', models.CharField(default=None, max_length=100, verbose_name='项目名称')),
                ('project_service', models.SmallIntegerField(verbose_name='业务类型')),
                ('project_type', models.CharField(max_length=10, verbose_name='编译类型')),
                ('project_local_command', models.TextField(blank=True, default=None, null=True, verbose_name='部署服务器要执行的命令')),
                ('project_repo_dir', models.CharField(default=None, max_length=100, verbose_name='本地仓库目录')),
                ('project_dir', models.CharField(default=None, max_length=100, verbose_name='代码目录')),
                ('project_exclude', models.TextField(blank=True, default=None, null=True, verbose_name='排除文件')),
                ('project_is_include', models.SmallIntegerField(default=0, verbose_name='包含或者排除')),
                ('project_address', models.CharField(default=None, max_length=100, verbose_name='版本仓库地址')),
                ('project_uuid', models.CharField(max_length=50, verbose_name='唯一id')),
                ('project_repo_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库用户名')),
                ('project_repo_passwd', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库密码')),
                ('project_repertory', models.CharField(choices=[('git', 'git'), ('svn', 'svn')], default=None, max_length=10, verbose_name='仓库类型')),
                ('project_status', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='是否激活')),
                ('project_pre_remote_command', models.TextField(blank=True, default=None, null=True, verbose_name='部署之后执行的命令')),
                ('project_remote_command', models.TextField(blank=True, default=None, null=True, verbose_name='部署之后执行的命令')),
                ('project_user', models.CharField(default=None, max_length=50, verbose_name='项目文件宿主')),
                ('project_model', models.CharField(choices=[('branch', 'branch'), ('tag', 'tag')], default=None, max_length=10, verbose_name='上线类型')),
                ('project_servers', models.TextField(verbose_name='目标主机')),
                ('project_logpath', models.CharField(max_length=500, verbose_name='日志路径')),
                ('project_target_root', models.CharField(max_length=200, verbose_name='部署路径')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_config', to='asset.Project_Assets')),
            ],
            options={
                'verbose_name': '项目发布管理',
                'verbose_name_plural': '项目管理表',
                'db_table': 'opsmanage_project_config',
                'permissions': (('project_read_project_config', '读取项目部署权限'), ('project_change_project_config', '更改项目部署权限'), ('project_add_project_config', '添加项目部署权限'), ('project_delete_project_config', '删除项目部署权限')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Project_Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.SmallIntegerField(default=None, verbose_name='用户id')),
                ('role', models.CharField(choices=[('deploy', 'deploy'), ('manage', 'manage')], max_length=10, verbose_name='项目角色')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='cicd.Project_Config')),
            ],
            options={
                'verbose_name': '项目发布管理',
                'verbose_name_plural': '项目角色管理表',
                'db_table': 'opsmanage_project_role',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='log_project_config',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_config', to='cicd.Project_Config'),
        ),
        migrations.AlterUniqueTogether(
            name='project_roles',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='project_config',
            unique_together={('project_env', 'project', 'project_name')},
        ),
    ]
